dist: xenial
language: csharp
solution: digital-ocean-base\Microting.DigitalOceanBase.sln
mono: none
dotnet: 3.1
addons:
  mariadb: '10.5'
script:
  - sudo mysql -e 'ALTER USER root@localhost IDENTIFIED VIA mysql_native_password'
  - dotnet restore
  - dotnet build Microting.DigitalOceanBase.sln
  - dotnet test -v n Microting.DigitalOceanBase.UnitTests/Microting.DigitalOceanBase.UnitTests.csproj
  - export GITVERSION=`git describe --abbrev=0 --tags | cut -d "v" -f 2`
  - echo $GITVERSION 
  - dotnet pack Microting.DigitalOceanBase.sln -c Release -o ./artifacts -p:PackageVersion=$GITVERSION
  - export FILENAME="/home/travis/build/microting/digital-ocean-base/artifacts/Microting.DigitalOceanBase.${GITVERSION}.nupkg"
  - echo $FILENAME
  - dotnet nuget push $FILENAME -k $NUGET_SECRET_KEY -s https://api.nuget.org/v3/index.json || true